FROM docker.cesanta.com/mg-iot-cloud-project-esp8266:release

ENV LANG C.UTF-8

# install dependencies
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN apt-get update
RUN apt-get install -y curl git
# install mongoose-os and tools
RUN git clone https://github.com/cesanta/mongoose-os.git
RUN curl -fsSL https://mongoose-os.com/downloads/mos/install.sh | /bin/bash
RUN mkdir /app
ADD . /app